name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Movie\ Catalog
      run: swift build -v
    - name: MovieCatalogTests
      run: swift test -v
